# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VMnmw0ubOv0myegj-jppB16r2TmT_fKQ
"""

from typing import List

def twoSum(nums: List[int], target: int) -> List[int]:
    # Create a dictionary to store the difference of target and the current number
    # and the corresponding index.
    num_dict = {}

    for i, num in enumerate(nums):
        diff = target - num
        if diff in num_dict:
            # Return the indices of the two numbers
            return [num_dict[diff], i]
        num_dict[num] = i